version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run start
    ports:
      - 8087:8087
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 8087
  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: testbr
